insert into course (name,description,teacher,school_hour,total_people) values ('语文','[nobis, consequuntur, aut, ut, id]','戴伟宸','56','0');
insert into course (name,description,teacher,school_hour,total_people) values ('数学','[ipsa, est, blanditiis, et, perferendis]','冯天翊','50','1');
insert into course (name,description,teacher,school_hour,total_people) values ('数学','[nesciunt, ducimus, expedita, sed, perspiciatis]','邱智辉','118','1');
insert into course (name,description,teacher,school_hour,total_people) values ('计算机','[ut, similique, voluptatem, molestiae, dolore]','田胤祥','42','4');
insert into course (name,description,teacher,school_hour,total_people) values ('语文','[quas, dolores, sit, maxime, voluptatem]','程金鑫','103','1');
insert into course (name,description,teacher,school_hour,total_people) values ('语文','[nam, debitis, consequuntur, corrupti, accusamus]','郝越彬','103','0');
insert into course (name,description,teacher,school_hour,total_people) values ('英语','[mollitia, in, debitis, aut, reiciendis]','金思源','53','4');
insert into course (name,description,teacher,school_hour,total_people) values ('体育','[id, doloremque, velit, aut, odit]','金风华','48','0');
insert into course (name,description,teacher,school_hour,total_people) values ('计算机','[qui, necessitatibus, et, quidem, libero]','孔擎苍','115','7');
insert into course (name,description,teacher,school_hour,total_people) values ('计算机','[quo, natus, non, numquam, illo]','白驰','79','2');
insert into course (name,description,teacher,school_hour,total_people) values ('体育','[nam, voluptas, sint, et, hic]','王浩宇','75','5');
insert into course (name,description,teacher,school_hour,total_people) values ('计算机','[dolorum, voluptatibus, itaque, tenetur, velit]','龙语堂','77','0');
insert into course (name,description,teacher,school_hour,total_people) values ('美术','[quas, numquam, deleniti, assumenda, tenetur]','彭笑愚','90','1');
insert into course (name,description,teacher,school_hour,total_people) values ('数学','[et, sed, voluptas, asperiores, nulla]','严靖琪','81','2');
insert into course (name,description,teacher,school_hour,total_people) values ('数学','[accusamus, minima, alias, enim, quam]','薛懿轩','50','5');
insert into course (name,description,teacher,school_hour,total_people) values ('计算机','[officia, fuga, perspiciatis, culpa, optio]','龙荣轩','96','7');
insert into course (name,description,teacher,school_hour,total_people) values ('语文','[error, sit, consectetur, voluptatum, est]','唐浩然','22','6');
insert into course (name,description,teacher,school_hour,total_people) values ('体育','[iusto, et, incidunt, facere, ex]','蒋琪','47','5');
insert into course (name,description,teacher,school_hour,total_people) values ('英语','[autem, voluptatibus, repellat, et, animi]','姚鹏','73','9');
insert into course (name,description,teacher,school_hour,total_people) values ('语文','[et, alias, et, voluptatem, similique]','陶瑞霖','118','5');
insert into course (name,description,teacher,school_hour,total_people) values ('计算机','[quaerat, nobis, et, soluta, ut]','孙振家','45','0');
insert into course (name,description,teacher,school_hour,total_people) values ('语文','[sapiente, facilis, voluptates, quo, laudantium]','林熠彤','114','8');
insert into course (name,description,teacher,school_hour,total_people) values ('计算机','[natus, nihil, est, et, sit]','武炫明','49','4');
insert into course (name,description,teacher,school_hour,total_people) values ('英语','[aut, quas, adipisci, vel, similique]','白语堂','111','1');
insert into course (name,description,teacher,school_hour,total_people) values ('美术','[ea, odit, amet, iste, minima]','邓博超','28','4');
insert into course (name,description,teacher,school_hour,total_people) values ('美术','[ut, et, cumque, quas, ad]','贺昊然','41','8');
insert into course (name,description,teacher,school_hour,total_people) values ('体育','[voluptatem, aperiam, at, nulla, qui]','任梓晨','23','4');
insert into course (name,description,teacher,school_hour,total_people) values ('数学','[laborum, dolores, ut, nobis, nihil]','蔡伟泽','45','0');
insert into course (name,description,teacher,school_hour,total_people) values ('计算机','[omnis, nihil, et, quo, ut]','黄凯瑞','104','9');
insert into course (name,description,teacher,school_hour,total_people) values ('计算机','[explicabo, est, omnis, placeat, occaecati]','龚文昊','58','4');
insert into net_course (name,description,url) values ('Rubens','[quibusdam, tenetur, ut, magnam, reiciendis, dolor, id, quis, modi, saepe]','www.xn---xn--vqq-929m341m.net');
insert into net_course (name,description,url) values ('Winslow Homer','[ullam, corrupti, ratione, qui, tempore, placeat, adipisci, sapiente, ipsam, ipsam]','www.xn---xn--674a-k13q0486c.org');
insert into net_course (name,description,url) values ('Cassatt','[non, tenetur, illum, voluptate, esse, ad, ut, ea, et, quis]','www.xn---xn--6f4a-k91u6962b.name');
insert into net_course (name,description,url) values ('Vincent','[magnam, veritatis, recusandae, itaque, in, illum, expedita, nam, porro, consequuntur]','www.xn---xn--0rs-815qw893a.com');
insert into net_course (name,description,url) values ('Klimt','[dolorem, officiis, ut, esse, laboriosam, qui, praesentium, rem, et, omnis]','www.xn---xn--6kq-to5sm861a.info');
insert into net_course (name,description,url) values ('Dali','[doloribus, perspiciatis, sequi, enim, tempore, iusto, iste, sit, qui, deleniti]','www.xn---xn--y7y-929m718s.biz');
insert into net_course (name,description,url) values ('Titian','[quis, natus, blanditiis, est, et, voluptatem, ut, aliquid, quidem, eos]','www.xn---xn--2vx-su8nn762b.org');
insert into net_course (name,description,url) values ('Gauguin','[voluptate, velit, suscipit, eum, voluptatem, voluptatum, fuga, ea, exercitationem, excepturi]','www.xn---xn--nfv-n00om3q.biz');
insert into net_course (name,description,url) values ('Ansel Adams','[quis, quia, minima, iste, sit, maxime, sunt, neque, dicta, repellat]','www.xn---xn--tp5a-fz0u6096a.io');
insert into net_course (name,description,url) values ('Picasso','[molestiae, atque, voluptatem, ut, repellendus, illum, delectus, cum, magnam, dolores]','www.xn---xn--5lw-929m441m.info');
insert into net_course (name,description,url) values ('Donatello','[ea, qui, aperiam, natus, et, qui, illum, illo, excepturi, id]','www.xn---xn--2vx-h94qo224a.com');
insert into net_course (name,description,url) values ('Donatello','[officiis, dicta, saepe, veniam, eos, odio, sit, est, quia, voluptatem]','www.xn---xn--vxs-n23nn26k.com');
insert into net_course (name,description,url) values ('Michelangelo','[perspiciatis, qui, qui, aut, et, ea, in, blanditiis, quae, dolor]','www.xn---xn--7mz-929m718s.net');
insert into net_course (name,description,url) values ('Rubens','[molestiae, nisi, eligendi, consectetur, ex, fuga, quaerat, molestiae, quos, et]','www.xn---xn--5lw-t67qv84m.co');
insert into net_course (name,description,url) values ('Cassatt','[mollitia, quia, ut, quia, fugit, ut, dolor, commodi, perferendis, illum]','www.xn---xn--zi7a-4x1rf08c.com');
insert into net_course (name,description,url) values ('Diego Rivera','[beatae, inventore, molestiae, vel, vel, distinctio, dolorem, aut, eveniet, in]','www.xn---xn--27q-u12y899a.name');
insert into net_course (name,description,url) values ('Caravaggio','[tempora, sunt, reprehenderit, asperiores, dicta, et, et, perferendis, assumenda, officiis]','www.xn---xn--boq-n00oj44h.com');
insert into net_course (name,description,url) values ('Durer','[facere, sit, odit, vel, modi, eligendi, vitae, eius, blanditiis, est]','www.xn---xn--920a-9e7oz232c.net');
insert into net_course (name,description,url) values ('Rembrandt','[aliquid, minima, maiores, nihil, consectetur, laborum, perspiciatis, ea, esse, eius]','www.xn---xn--l4t-d33p.co');
insert into net_course (name,description,url) values ('Munch','[dolor, ex, laborum, eligendi, et, nihil, architecto, dolorem, porro, id]','www.xn---xn--txs-fh8nl85r.name');
insert into net_course (name,description,url) values ('Degas','[qui, deserunt, sit, labore, natus, a, quasi, a, cum, quos]','www.xn---xn--z05a-455q4919c.info');
insert into net_course (name,description,url) values ('Da Vinci','[voluptates, aliquid, repellendus, modi, quam, minima, aliquid, enim, vero, tenetur]','www.xn---xn--6i6a-4d7sq97d.io');
insert into net_course (name,description,url) values ('Rothko','[voluptas, omnis, maxime, qui, magnam, voluptate, ullam, quam, ab, earum]','www.xn---xn--e1t-n93un31n.net');
insert into net_course (name,description,url) values ('El Greco','[tempora, dolores, fugiat, possimus, qui, provident, repellendus, est, saepe, voluptate]','www.xn---xn--69s-r93q44b.io');
insert into net_course (name,description,url) values ('Chagall','[voluptas, voluptas, esse, et, nobis, quia, quia, dolorem, est, alias]','www.xn---xn--tp5a-439uw60e.net');
insert into net_course (name,description,url) values ('Durer','[fugit, deserunt, consectetur, omnis, eos, doloremque, qui, sit, esse, voluptatem]','www.xn---xn--7mz-wb8rn764a.org');
insert into net_course (name,description,url) values ('Botticelli','[doloribus, et, at, et, est, impedit, ducimus, maiores, quod, laudantium]','www.xn---xn--mpr-o38r871a.io');
insert into net_course (name,description,url) values ('Monet','[eaque, ut, iusto, saepe, et, fugiat, sit, corporis, sit, est]','www.xn---xn--wou-re3mq872d.net');
insert into net_course (name,description,url) values ('Cezanne','[eaque, quasi, saepe, assumenda, aspernatur, quo, voluptas, exercitationem, ut, sit]','www.xn---xn--5i5a-us4y423i.org');
insert into net_course (name,description,url) values ('Chagall','[minus, ut, magnam, quisquam, amet, et, incidunt, est, quia, consequuntur]','www.xn---xn--27q-n00om3q.net');
insert into teacher_show (title,description,editor,author,gmt_create,page_view,title_img) values ('Dark Lager! 金伟宸  的个人风采','[amet, eaque, eum, illum, repellat]','周峻熙','叶智辉','901688086459','3','https://s3.amazonaws.com/uifaces/faces/twitter/nelsonjoyce/128.jpg');
insert into teacher_show (title,description,editor,author,gmt_create,page_view,title_img) values ('Belgian Strong Ale! 张远航  的个人风采','[ipsum, voluptatibus, sint, molestiae, ut]','萧智宸','魏健雄','1601026284173','6','https://s3.amazonaws.com/uifaces/faces/twitter/carlosblanco_eu/128.jpg');
insert into teacher_show (title,description,editor,author,gmt_create,page_view,title_img) values ('Strong Ale! 王琪  的个人风采','[tempore, nihil, minima, qui, ut]','赖天磊','邱钰轩','1111887472940','4','https://s3.amazonaws.com/uifaces/faces/twitter/johncafazza/128.jpg');
insert into teacher_show (title,description,editor,author,gmt_create,page_view,title_img) values ('European Amber Lager! 唐苑博  的个人风采','[tempora, officia, fugiat, sed, consectetur]','杨文博','贺苑博','1315628324415','1','https://s3.amazonaws.com/uifaces/faces/twitter/iamjdeleon/128.jpg');
insert into teacher_show (title,description,editor,author,gmt_create,page_view,title_img) values ('Light Hybrid Beer! 龙风华  的个人风采','[quis, nihil, dolor, dolor, ducimus]','白晟睿','薛正豪','802127935005','9','https://s3.amazonaws.com/uifaces/faces/twitter/low_res/128.jpg');
insert into teacher_show (title,description,editor,author,gmt_create,page_view,title_img) values ('Scottish And Irish Ale! 周思远  的个人风采','[est, laborum, facere, occaecati, ad]','郝子轩','朱锦程','1186723833479','6','https://s3.amazonaws.com/uifaces/faces/twitter/jasonmarkjones/128.jpg');
insert into teacher_show (title,description,editor,author,gmt_create,page_view,title_img) values ('Light Lager! 于凯瑞  的个人风采','[non, nam, vel, unde, numquam]','石鹏飞','罗远航','1250564891255','7','https://s3.amazonaws.com/uifaces/faces/twitter/thomasschrijer/128.jpg');
insert into teacher_show (title,description,editor,author,gmt_create,page_view,title_img) values ('Sour Ale! 田昊然  的个人风采','[commodi, eveniet, dolores, rerum, enim]','方泽洋','杜志泽','1264237488462','3','https://s3.amazonaws.com/uifaces/faces/twitter/davidsasda/128.jpg');
insert into teacher_show (title,description,editor,author,gmt_create,page_view,title_img) values ('Bock! 袁文昊  的个人风采','[molestias, doloribus, id, totam, et]','彭雨泽','杨嘉懿','1198279879890','6','https://s3.amazonaws.com/uifaces/faces/twitter/michzen/128.jpg');
insert into teacher_show (title,description,editor,author,gmt_create,page_view,title_img) values ('Light Hybrid Beer! 汪子涵  的个人风采','[aspernatur, eos, in, dolorem, vel]','范思聪','夏雨泽','938654149559','1','https://s3.amazonaws.com/uifaces/faces/twitter/lu4sh1i/128.jpg');
insert into teacher_show (title,description,editor,author,gmt_create,page_view,title_img) values ('English Brown Ale! 林弘文  的个人风采','[nam, et, et, nobis, ut]','雷天宇','曾峻熙','1048111056547','7','https://s3.amazonaws.com/uifaces/faces/twitter/91bilal/128.jpg');
insert into teacher_show (title,description,editor,author,gmt_create,page_view,title_img) values ('English Pale Ale! 贾鹏煊  的个人风采','[enim, a, mollitia, exercitationem, qui]','姜哲瀚','雷炫明','1217437498355','4','https://s3.amazonaws.com/uifaces/faces/twitter/mactopus/128.jpg');
insert into teacher_show (title,description,editor,author,gmt_create,page_view,title_img) values ('Light Hybrid Beer! 蒋明轩  的个人风采','[repellat, dolores, vel, eum, consequatur]','董航','戴天宇','747552332456','4','https://s3.amazonaws.com/uifaces/faces/twitter/rmlewisuk/128.jpg');
insert into teacher_show (title,description,editor,author,gmt_create,page_view,title_img) values ('Bock! 陆越彬  的个人风采','[eos, quos, non, ad, et]','薛鑫鹏','洪明辉','951621271368','1','https://s3.amazonaws.com/uifaces/faces/twitter/d_nny_m_cher/128.jpg');
insert into teacher_show (title,description,editor,author,gmt_create,page_view,title_img) values ('Amber Hybrid Beer! 许思  的个人风采','[voluptatem, harum, aperiam, aliquam, voluptatum]','姚子骞','洪远航','1341847717267','1','https://s3.amazonaws.com/uifaces/faces/twitter/michaelmartinho/128.jpg');
insert into teacher_show (title,description,editor,author,gmt_create,page_view,title_img) values ('Pilsner! 顾睿渊  的个人风采','[consequatur, dignissimos, eos, aut, recusandae]','谭风华','冯驰','1526717507677','5','https://s3.amazonaws.com/uifaces/faces/twitter/cofla/128.jpg');
insert into teacher_show (title,description,editor,author,gmt_create,page_view,title_img) values ('Belgian And French Ale! 贾子涵  的个人风采','[aliquam, illo, numquam, alias, est]','梁语堂','宋文博','771440618740','0','https://s3.amazonaws.com/uifaces/faces/twitter/gauravjassal/128.jpg');
insert into teacher_show (title,description,editor,author,gmt_create,page_view,title_img) values ('Belgian And French Ale! 汪立轩  的个人风采','[non, nesciunt, a, quidem, consectetur]','于浩轩','邹振家','721117782474','3','https://s3.amazonaws.com/uifaces/faces/twitter/myastro/128.jpg');
insert into teacher_show (title,description,editor,author,gmt_create,page_view,title_img) values ('Fruit Beer! 萧雨泽  的个人风采','[commodi, perspiciatis, nihil, atque, est]','孟浩','夏语堂','834087200874','3','https://s3.amazonaws.com/uifaces/faces/twitter/mhesslow/128.jpg');
insert into teacher_show (title,description,editor,author,gmt_create,page_view,title_img) values ('Fruit Beer! 邵子骞  的个人风采','[adipisci, magni, deleniti, in, voluptates]','阎懿轩','杜天宇','650128394463','7','https://s3.amazonaws.com/uifaces/faces/twitter/goddardlewis/128.jpg');
insert into teacher_show (title,description,editor,author,gmt_create,page_view,title_img) values ('English Pale Ale! 张昊然  的个人风采','[necessitatibus, voluptatem, est, quod, saepe]','邓明杰','蔡明杰','693988970764','6','https://s3.amazonaws.com/uifaces/faces/twitter/kolsvein/128.jpg');
insert into teacher_show (title,description,editor,author,gmt_create,page_view,title_img) values ('Bock! 孔博文  的个人风采','[beatae, nihil, cum, doloremque, et]','吕明辉','夏瑾瑜','980236133555','7','https://s3.amazonaws.com/uifaces/faces/twitter/matt3224/128.jpg');
insert into teacher_show (title,description,editor,author,gmt_create,page_view,title_img) values ('English Pale Ale! 谭君浩  的个人风采','[sapiente, et, recusandae, quia, pariatur]','韩浩','秦泽洋','1460693072660','6','https://s3.amazonaws.com/uifaces/faces/twitter/salimianoff/128.jpg');
insert into teacher_show (title,description,editor,author,gmt_create,page_view,title_img) values ('Wood-aged Beer! 方语堂  的个人风采','[esse, sunt, nulla, odio, adipisci]','苏越彬','李烨霖','1246867144046','7','https://s3.amazonaws.com/uifaces/faces/twitter/kazaky999/128.jpg');
insert into teacher_show (title,description,editor,author,gmt_create,page_view,title_img) values ('Vegetable Beer! 郝金鑫  的个人风采','[est, ipsam, neque, nihil, et]','陈旭尧','蔡展鹏','1091632815564','1','https://s3.amazonaws.com/uifaces/faces/twitter/tgormtx/128.jpg');
insert into teacher_show (title,description,editor,author,gmt_create,page_view,title_img) values ('Scottish And Irish Ale! 钟烨伟  的个人风采','[molestias, illo, voluptas, beatae, quia]','吕修洁','宋耀杰','682414792666','8','https://s3.amazonaws.com/uifaces/faces/twitter/lvovenok/128.jpg');
insert into teacher_show (title,description,editor,author,gmt_create,page_view,title_img) values ('European Amber Lager! 周弘文  的个人风采','[quia, ut, adipisci, pariatur, odit]','田航','苏嘉懿','1482701381052','3','https://s3.amazonaws.com/uifaces/faces/twitter/n_tassone/128.jpg');
insert into teacher_show (title,description,editor,author,gmt_create,page_view,title_img) values ('European Amber Lager! 姚潇然  的个人风采','[dolorem, odio, est, ea, et]','郝熠彤','邵天宇','906790715686','7','https://s3.amazonaws.com/uifaces/faces/twitter/to_soham/128.jpg');
insert into teacher_show (title,description,editor,author,gmt_create,page_view,title_img) values ('Scottish And Irish Ale! 卢智辉  的个人风采','[cupiditate, pariatur, molestiae, fugiat, et]','卢致远','于弘文','848858623252','5','https://s3.amazonaws.com/uifaces/faces/twitter/tomas_janousek/128.jpg');
insert into teacher_show (title,description,editor,author,gmt_create,page_view,title_img) values ('Light Hybrid Beer! 邵浩宇  的个人风采','[aspernatur, voluptatem, quo, neque, sed]','黄航','邓鸿煊','1481284996859','2','https://s3.amazonaws.com/uifaces/faces/twitter/michaelcolenso/128.jpg');
